steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/krazius-solutions:$COMMIT_SHA", "."]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/krazius-solutions:$COMMIT_SHA"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "krazius-solutions"
      - "--image"
      - "gcr.io/$PROJECT_ID/krazius-solutions:$COMMIT_SHA"
      - "--region"
      - "europe-west1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "3000"
      - "--memory"
      - "512Mi"
      - "--cpu"
      - "1"
      - "--max-instances"
      - "10"
      - "--service-account"
      - "krazius-cloudbuild@$PROJECT_ID.iam.gserviceaccount.com"

# Use dedicated service account for builds
serviceAccount: "projects/$PROJECT_ID/serviceAccounts/krazius-cloudbuild@$PROJECT_ID.iam.gserviceaccount.com"

images:
  - "gcr.io/$PROJECT_ID/krazius-solutions:$COMMIT_SHA"
